x -> X
user curl-type HTTP method option

diff --git a/arc/arc b/arc/arc
--- a/arc/arc
+++ b/arc/arc
@@ -116,7 +116,7 @@ sethttp() {
     "delete"|"DELETE")
       httpmethod="DELETE" ;;
     *)
-      echo >&2 "invalid argument \`$http\` for \`-x\`" && usage && exit 2 ;;
+      echo >&2 "invalid argument \`$http\` for \`-X\`" && usage && exit 2 ;;
   esac
 }
 
@@ -149,7 +149,7 @@ license() {
 
 examples() {
   echo >&2 "$0 courses";
-  echo >&2 "$0 -x PUT users/self/settings -F 'manual_mark_as_read=false'";
+  echo >&2 "$0 -X PUT users/self/settings -F 'manual_mark_as_read=false'";
   echo >&2 "$0 <token> DELETE <domain> users/self/activity_stream";
   echo >&2 "$0 <token> POST <domain> users/self/files -F 'url=http://www.canvaslms.com/img/logo_instructure.png' -F 'name=instructure.png'";
 }
@@ -311,7 +311,7 @@ else
           setconfig ;;
         r)
           setrenderer $OPTARG ;;
-        x)
+        X)
           sethttp $OPTARG ;;
         d)
           arc_domain="$OPTARG" ;;
