studio v1.0.0

diff --git a/studio/studio b/studio/studio
--- a/studio/studio
+++ b/studio/studio
@@ -19,315 +19,58 @@
 
 # HELPER FUNCTIONS #############################################################
 # ##############################################################################
-
-logo() {
-  echo '
-                  AAA
-                 AAAAA
-                AAAAAAA
-              AAAA   AAAA
-             AAA       AAA
-          AAAAAAA     AAAAAAA
-       AAAAAAAAAAAA AAAAAAAAAAAA
-    AAAAAAAA  AAAAAAAAAA  AAAAAAAAAA
-AAAAAAAAAA      AAAAAA      AAAAAAAAAAAA
-              AAAAAAAAAA
-          AAAAAAAAAAAAAAAAAA
-      AAAAAAAAAAAA  AAAAAAAAAAAAA
-  AAAAAAAAAAA            AAAAAAAAAAAAA
-AAAAAAAA                        AAAAAAAA
-  '
-}
-
-dependency() {
-  declare -a dep=("$@")
-  command -v ${dep[2]} > /dev/null 2>&1 || prompt ${dep[@]}
-}
-
-prompt() {
-  declare -a dep=("$@")
-  clear
-  echo >&2 "studio-cli requires ${dep[1]} (${dep[3]}) but it's not installed"
-  echo >&2 "would you like to install it now?"
-  select yn in "Yes" "No"; do
-    case $yn in
-      Yes ) install ${dep[@]}; dependency ${dep[@]}; break;;
-      No ) manualinstall ${dep[@]}; exit;;
-    esac
-  done
-}
-
-install() {
-  declare -a dep=("$@")
-  clear
-  echo >&2 "studio-cli will attempt to install ${dep[1]} (${dep[3]})"
-  hr
-  if [ ${dep[3]} = "npm" ]; then
-    command -v ${dep[3]} > /dev/null 2>&1 && npm install -g "${dep[1]}" || manualinstall ${dep[@]} ""
-  elif [ ${dep[3]} = "pip" ]; then
-    command -v ${dep[3]} > /dev/null 2>&1 && pip2 install "${dep[1]}" || manualinstall ${dep[@]} ""
-  else
-    manualinstall ${dep[@]} ""
-  fi
-  local status=$(echo $?)
-  if [ "$status" -gt 0 ]; then
-    manualinstall ${dep[@]} $status
-  fi
-  hr
-  echo >&2 "${dep[1]} (${dep[3]}) successfully installed"
-}
-
-manualinstall() {
-  declare -a dep=("$@")
-  if [ ${#dep[@]} -gt 4 ]; then
-    hr
-    echo "studio-cli was unable to install ${dep[1]} (${dep[3]})"
-    if [ ${dep[3]} = "npm" ]; then
-      echo >&2 "\`npm install -g ${dep[1]}\` failed"
-    elif [ ${dep[3]} = "pip" ]; then
-      echo >&2 "\`pip2 install ${dep[1]}\` failed"
-    else
-      echo >&2 "\`curl\` is a system package"
-    fi
-  fi
-  if [ ${dep[3]} = "npm" ]; then
-    echo >&2 "Try using \`npm install -g ${dep[1]}\` to manually install"
-  elif [ ${dep[3]} = "pip" ]; then
-    echo >&2 "Try using \`pip2 install ${dep[1]}\` to manually install"
-  else
-    echo >&2 "${dep[1]} must be installed using a system package manager"
-  fi
-  exit 127
-}
-
-hr() {
-  local start=$'\e(0' end=$'\e(B' line='qqqqqqqqqqqqqqqq'
-  local cols=${COLUMNS:-$(tput cols)}
-  while ((${#line} < cols)); do line+="$line"; done
-  echo >&2 ""
-  printf '%s%s%s\n' "$start" "${line:0:cols}" "$end"
-  echo >&2 ""
-}
-
-outputrenderer="| json | pygmentize -l json"
-setrenderer() {
-  local renderer="$1"
-  case $renderer in
-    "plain")
-      outputrenderer="" ;;
-    "color")
-      outputrenderer="| json | pygmentize -l json" ;;
-    *)
-      echo >&2 "invalid argument \`$renderer\` for \`-r\`" && usage && exit 2 ;;
-  esac
-}
-
-httpmethod="GET"
-sethttp() {
-  local http="$1"
-  case $http in
-    "get"|"GET")
-      httpmethod="GET" ;;
-    "post"|"POST")
-      httpmethod="POST" ;;
-    "put"|"PUT")
-      httpmethod="PUT" ;;
-    "delete"|"DELETE")
-      httpmethod="DELETE" ;;
-    *)
-      echo >&2 "invalid argument \`$http\` for \`-X\`" && usage && exit 2 ;;
-  esac
-}
-
-# HELP STUFF ###################################################################
-# ##############################################################################
-
-help() {
-  usage
-  exit;
-}
-
-verbosehelp() {
-  curl --tlsv1.2 --retry 2 --retry-connrefused -s -S -g -X GET "https://raw.githubusercontent.com/thedannywahl/inst-api/master/studio/README" | less
-  exit;
-}
-
-usage() {
-  echo -e 2>&1 "Usage: studio [options] method\r\nHelp:  studio -h"
-}
-
-version() {
-  logo
-  echo >&2 "       studio-cli version 0.3.1"
-  exit
-}
-
-license() {
-  curl --tlsv1.2 --retry 2 --retry-connrefused -s -S -g -X GET "https://www.apache.org/licenses/LICENSE-2.0.txt" | less
-  exit
-}
-
-# HANDLE DEPENDENCIES ##########################################################
-# Requires: jsontool (npm), pygmentize (pip), curl, and getopts                #
-# ##############################################################################
-
-# null | name | executable | repository
-# `null` is a hacky shift to avoid string manipulation of
-# multi-dimensional array when passed as a parameter
-json=("" "json" "json" "npm")
-pygments=("" "pygments" "pygmentize" "pip")
-shellgetopts=("" "getopts" "getopts" "system")
-curl=("" "curl" "curl" "system")
-dependencies=(JSON=${json[@]} PYGMENTS=${pygments[@]} SHELLGETOPTS=${shellgetopts[@]} CURL=${curl[@]})
-for dep in "${dependencies[@]}"
-  do dependency ${dep[@]}
-done
+cmd=${0##*/}
+ver="1.0.0"
+$(insthelp checkdeps) > /dev/null 2>&1
+curlopts=$(insthelp curlopts)
+outputrenderer=$(insthelp setrenderer)
+httpmethod=$(insthelp sethttp)
 
 # PREF FILE ####################################################################
 # ##############################################################################
-
-studio_domain=""
-studio_email=""
-studio_password=""
-readconfig() {
-  if [ -f ~/.inst ]; then
-    . ~/.inst
-    if [ -z $studio_domain ]; then
-      echo >&2 "unable to read domain from config file \`~/.inst\`"
-      echo >&2 "It must be manually added or repaired.  Format:"
-      echo >&2 "studio_domain=\"<domain>\""
-      exit 2
-    fi
-    if [ -z $studio_email ]; then
-      echo >&2 "unable to read token from config file \`~/.inst\`"
-      echo >&2 "It must be manually added or repaired.  Format:"
-      echo >&2 "studio_email=\"<token>\""
-      exit 2;
-    fi
-    if [ -z $studio_password ]; then
-      echo >&2 "unable to read token from config file \`~/.inst\`"
-      echo >&2 "It must be manually added or repaired.  Format:"
-      echo >&2 "studio_password=\"<token>\""
-      exit 2;
-    fi
-  else
-    clear
-    echo >&2 "config file \`~/.inst\` not found"
-    echo >&2 "would you like to create it now?"
-    select yn in "Yes" "No"; do
-      case $yn in
-        Yes )
-          setconfig; break ;;
-        No )
-          clear
-          echo >&2 "studio-cli requires a config file or use \`-d\`, \`-e\`, and \`-p\`"
-          usage; exit 2 ;;
-      esac
-    done
+if [ -f ~/.inst ]; then
+  . ~/.inst
+  if [ -z $studio_domain ] || [ -z $studio_email ] || [ -z $studio_password ]; then
+   $(insthelp setconfig $cmd)
+   exit
   fi
-}
+else
+ $(insthelp setconfig $cmd)
+ exit
+fi
 
-setconfig() {
-  clear
-  echo -e "DO NOT create a config file on a shared system"
-  echo >&2 "other system users will be able to authenticate using your"
-  echo >&2 "saved credentials.  Instead use the \`-d\`, \`-e\`, and \`-p\` options"
-  echo >&2 "Do you wish to proceed?"
-  select ok in "Okay" "Cancel"; do
-    case $ok in
-      Okay)
-        touch ~/.inst
-        if [ $? = 0 ]; then
-          setdomain
-          setemail
-          setpassword
-          readconfig
-        else
-          clear
-          echo >&2 "unable to create config file \`~/.inst\`"
-          echo >&2 "please ensure that you have appropriate permissions"
-          exit 2
-        fi; break;;
-      Cancel)
-        clear
-        echo >&2 "Enter your command again using the \`-d\`, \`-e\`, and \`-p\` options"
-        usage;
-        exit 0;;
-    esac
-  done
-  clear
-}
-
-setdomain() {
-  clear
-  echo >&2 "what is your Studio subdomain?"
-  echo >&2 "https://<subdomain>.instructuremedia.com"
-  read studiodomain
-  echo "studio_domain=\"$studiodomain\"" >> ~/.inst
-}
-
-setemail() {
-  clear
-  echo >&2 "What is your Studio login email address?"
-  read studioemail
-  echo >&2 "studio_email=\"$studioemail\"" >> ~/.inst
-}
-
-setpassword() {
-  clear
-  echo >&2 "What is your Studio login password?"
-  read arcpassword
-  echo >&2 "studio_password=\"$studiopassword\"" >> ~/.inst
-}
-
-# OUTPUT FILE ##################################################################
-# ##############################################################################
-
-outputpath=""
-setoutput() {
-  if [ -f $1 ]; then
-    clear
-    echo "\`$1\` exists, overwrite it?"
-    select ow in "Yes" "No"; do
-      case $ow in
-        Yes )
-          outputpath="> $1"; break ;;
-        No )
-          echo >&2 "will not overwrite file."
-          exit 1
-      esac
-    done
-  else
-    outputpath="> $1"
-  fi
-}
 # PARSE OPTS ###################################################################
 # ##############################################################################
-
 formopts=""
 if [ $# -eq 0 ] && [ ! -f ~/.inst ]; then
-  readconfig
-  help
+  $(insthelp readconfig $cmd)
+  $(insthelp help $cmd)
+  exit 2
 elif [ $# -eq 0 ] && [ -f ~/.inst ]; then
-  help
+  $(insthelp help $cmd)
+  exit 2
 else
   while [ $# -gt 0 ] && [ "$1" != "--" ]; do
-    while getopts ":hlvcsr:X:e:p:d:o:F:" opt; do
+    while getopts ":hlvcsr:x:X:e:p:d:o:f:F:" opt; do
       case $opt in
         h)
-          verbosehelp ;;
+          $(insthelp verbosehelp $cmd)
+          exit ;;
         l)
-          license ;;
+          $(insthelp license)
+          exit ;;
         v)
-          version ;;
+          $(insthelp version $cmd $ver)
+          exit ;;
         c)
-          setconfig ;;
+          $(insthelp setconfig $cmd)
+          exit ;;
         s)
           sample=true ;;
         r)
-          setrenderer $OPTARG ;;
-        X)
-          sethttp $OPTARG ;;
+          outputrenderer=$(insthelp setrenderer $OPTARG) ;;
+        X|x)
+          $(insthelp sethttp $OPTARG) ;;
         d)
           studio_domain="$OPTARG" ;;
         e)
@@ -335,15 +78,18 @@ else
         p)
           studio_password="$OPTARG" ;;
         o)
-          setoutput $OPTARG;;
-        F)
-          # -F opts are concatenated and
-          # transparently passed to curl
+          outputpath=$(insthelp setoutput $OPTARG ${BASH_ARGV[0]})
+          if [ "$outputpath" = "ERR" ]; then exit 1; fi ;;
+        F|f)
           formopts="$formopts -F $OPTARG" ;;
         \?)
-          echo >&2 "invalid option: \`-$OPTARG\`" && usage && exit 2 ;;
+          printf >&2 "Invalid option: \`-$OPTARG\`\r\n"
+          $(insthelp help $cmd)
+          exit 2 ;;
         :)
-          echo >&2 "missing argument for \`-$OPTARG\`" && usage && exit 2 ;;
+          printf >&2 "Missing argument for \`-$OPTARG\`\r\n"
+          $(insthelp help $cmd)
+          exit 2 ;;
       esac
     done
     shift $((OPTIND-1))
@@ -352,8 +98,8 @@ else
       shift
       break
     else
-      echo "No API method provided!"
-      usage
+      printf >&2 "No API method provided\r\n"
+      $(insthelp help $cmd)
       exit 2
     fi
   done
@@ -365,12 +111,11 @@ fi
 
 # BUILD COMMAND ################################################################
 # ##############################################################################
-
 if [ -z "$studio_domain" ] && [ -z "$studio_email" ] && [ -z "$studio_password" ]; then
-  readconfig
+  $(insthelp readconfig $cmd)
 elif [ -z "$studio_domain" ] || [ -z "$studio_email" ] || [ -z "$studio_password" ]; then
-  echo >&2 "\`-d\`, \`-e\`, and \`-p\` are required when not using a config file"
-  usage
+  printf >&2 "\`-d\`, \`-e\`, and \`-p\` are required when not using a config file\r\n"
+  $(insthelp help $cmd)
   exit 2
 fi
 
@@ -380,40 +125,32 @@ fi
 
 # START SESSION ################################################################
 # ##############################################################################
-
-session=""
-userid=""
-token=""
-curlopts="--tlsv1.2 --retry 2 --retry-connrefused -s -S -g"
-
 session=$(curl $curlopts -H "Content-Type: application/json" --data '{"email":"'$studio_email'","password":"'$studio_password'"}' -X POST "https://$studio_domain.instructuremedia.com/api/auth/session")
 if [ $? -gt 0 ]; then
-  echo >&2 "Unable to generate a session.  Please ensure that your credentials are accurate."
+  printf >&2 "Unable to generate a session.  Please ensure that your credentials are accurate.\r\n"
   exit 2
 fi
 token=$(echo "$session" | python -c 'import sys, json; print json.load(sys.stdin)["session"]["token"]')
 if [ $? -gt 0 ]; then
-  echo >&2 "Unable to find session token."
+  printf >&2 "Unable to find session token.\r\n"
   exit 2
 fi
 userid=$(echo "$session" | python -c 'import sys, json; print json.load(sys.stdin)["session"]["user"]["id"]')
 if [ $? -gt 0 ]; then
-  echo >&2 "Unable to find session userid."
+  printf >&2 "Unable to find session userid.\r\n"
   exit 2
 fi
 
 # BUILD COMMAND ################################################################
 # ##############################################################################
-
 command="curl $curlopts -H 'Authorization: Bearer user_id=\"$userid\", token=\"$token\"' -X $httpmethod \"https://$studio_domain.instructuremedia.com/api/$path\" $formopts $outputrenderer $outputpath"
 if [ "$sample" = true ]; then
-  echo "$command"
+  printf >&2 "$command\r\n"
 else
   eval $command
 fi
 
 # DELETE SESSION ###############################################################
 # ##############################################################################
-
-closesession="curl --tlsv1.2 --retry 2 --retry-connrefused -s -S -g -H 'Authorization: Bearer user_id=\"$userid\", token=\"$token\"' -X DELETE https://$arc_domain.instructuremedia.com/api/auth/session"
+closesession="curl $curlopts 'Authorization: Bearer user_id=\"$userid\", token=\"$token\"' -X DELETE https://$arc_domain.instructuremedia.com/api/auth/session"
 eval $closesession
